const usernames = [
  "daenerys_targaryen",
  "cersei_lannister",
  "sansa_stark",
  "arya_stark",
  "brienne_of_tarth",
  "margaery_tyrell",
  "catelyn_stark",
  "olenna_tyrell",
  "ygritte",
  "melisandre",
  "shaen",
  "missandei",
  "lyanna_stark",
  "asha_greyjoy",
  "meera_reed",
  "lysa_arryn",
  "talisa_maegyr",
  "gilly",
  "shireen_baratheon",
  "myrcella_baratheon",
  "lyanna_mormont",
  "dacey_mormont",
  "selyse_baratheon",
  "arianne_martell",
  "mya_stone",
  "falia",
  "khalessi",
  "alys_karstark",
  "ros",
  "jeyne_poole",
  "olenna_tyrell",
  "lady_stoneheart",
  "tansy",
  "dorne_martell",
  "lyanna_stark",
  "sansa_stark",
  "ygritte",
  "asha_greyjoy",
  "tansa",
  "meryn_trant's_mother",
  "shiera_seastar",
  "alysanne_hightower",
  "brenda",
  "mhaegen",
  "meera_reed",
  "elia_martell",
  "lady_stark",
  "cersei_baratheon",
  "mya_stone",
  "varys'_female_spy",
  "catelyn_stark",
  "brianna",
  "alysanne_velaryon",
  "jeyne_westerling",
  "katherine_stark",
  "lynesse_hightower",
  "falyse_stokeworth",
  "margaery's_grandmother",
  "lady_tanda",
  "lysa_tully",
  "daena_targaryen",
  "mya_stone",
  "penny",
  "nym_sand",
  "tyene_sand",
  "obara_sand",
  "eleanor",
  "nymeria_sand",
  "rhaenys_targaryen",
  "dacey_mormont",
  "lady_mormont",
  "falia",
  "alys_karstark",
  "jeyne_poole",
  "mya_stone",
  "nym_sand",
  "selyse_baratheon",
  "lady_brienne",
  "falia",
  "khal_drogo's_widow",
  "daena_targaryen",
  "ashara_dayne",
  "shiera_seastar",
  "lady_stoneheart",
  "myrcella_baratheon",
  "beryn",
  "khal_drogo's_mother",
  "walda_frey",
  "catelyn_stark",
  "falia",
  "alysane_velaryon",
  "lady_margaery",
  "lady_leona",
  "lady_tanda",
  "arianne_martell",
  "lysa_arryn",
  "talisa_stark",
  "sophie",
  "catelyn_tully",
   "harry", "hermione", "ron", "albus", "severus", "tom", "draco", "sirius", "remus", "rubeus",
  "minerva", "ginny", "fred", "george", "luna", "neville", "cedric", "cho", "narcissa", "lucius",
  "bellatrix", "peter", "arthur", "molly", "fleur", "viktor", "dobby", "newt", "percy", "charlie",
  "bill", "kingsley", "cornelius", "gellert", "quirinus", "rolanda", "pomona", "horace", "argus", "gilderoy",
  "nicolas", "frank", "alice", "marvolo", "morfin", "gregorovitch", "mundungus", "stan", "ernie", "lee",
  "angelina", "parvati", "padma", "lavender", "seamus", "dean", "justin", "terry", "anthony", "michael",
  "zacharias", "susan", "hannah", "ernie", "millicent", "theodore", "blaise", "pansy", "vincent", "gregory",
  "marcus", "oliver", "cormac", "demelza", "roger", "adrian", "katie", "alicia", "terence", "amelia",
  "andromeda", "ted", "cassandra", "charity", "wilhelmina", "armando", "phineas", "elizabeta", "bathilda", "everard",
  "godric", "helga", "rowena", "salazar", "hedwig", "fawkes", "buckbeak", "aragog", "norbert", "trevor"

];

/**
 * Returns a random username from the predefined list.
 */
// const usernames = [
//   "abhishek", "deneres", "arya", "sansa", "catelyn", "cersi", "bryan", "margery", "daenerys", "shae"
// ]
export function getRandomUsername() {
  const randomIndex = Math.floor(Math.random() * usernames.length);
  return usernames[randomIndex];
}

console.log(getRandomUsername());

